
FROM python:3.9-slim
WORKDIR /app

COPY ./requirements.txt /worker/requirements.txt
COPY ./app /app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /worker/requirements.txt

# Команда запуска worker
CMD ["python", "rabbit_worker.py"]